Importing the dependencies

In [1]:
import numpy as np
import pandas as pd
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

Data Collection and Preprocessing

In [2]:
# loading the data from the csv file to apandas dataframe
movies_data = pd.read_csv('/content/movies.csv')

In [3]:
# printing the first 5 rows of the dataframe
movies_data.head()

index     budget                                    genres  \
0      0  237000000  Action Adventure Fantasy Science Fiction   
1      1  300000000                  Adventure Fantasy Action   
2      2  245000000                    Action Adventure Crime   
3      3  250000000               Action Crime Drama Thriller   
4      4  260000000          Action Adventure Science Fiction   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  culture clash future space war space colony so...                en   
1  ocean drug abuse exotic island east india trad...                en   
2         spy based on novel secret agent sequel mi6                en   
3  dc comics crime fighter terrorist secret ident...                en   
4  based on novel mars medallion space travel pri...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  ... runtime  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577  ...     162   
1  Captain Barbossa, long believed to be dead, ha...  139.082615  ...     169   
2  A cryptic message from Bond’s past sends him o...  107.376788  ...     148   
3  Following the death of District Attorney Harve...  112.312950  ...     165   
4  John Carter is a war-weary, former military ca...   43.926995  ...     132   

                                    spoken_languages    status  \
0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1           [{"iso_639_1": "en", "name": "English"}]  Released   
2  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3           [{"iso_639_1": "en", "name": "English"}]  Released   
4           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title vote_average vote_count  \
0                                    Avatar          7.2      11800   
1  Pirates of the Caribbean: At World's End          6.9       4500   
2                                   Spectre          6.3       4466   
3                     The Dark Knight Rises          7.6       9106   
4                               John Carter          6.1       2124   

                                                cast  \
0  Sam Worthington Zoe Saldana Sigourney Weaver S...   
1  Johnny Depp Orlando Bloom Keira Knightley Stel...   
2  Daniel Craig Christoph Waltz L\u00e9a Seydoux ...   
3  Christian Bale Michael Caine Gary Oldman Anne ...   
4  Taylor Kitsch Lynn Collins Samantha Morton Wil...   

                                                crew           director  
0  [{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...      James Cameron  
1  [{'name': 'Dariusz Wolski', 'gender': 2, 'depa...     Gore Verbinski  
2  [{'name': 'Thomas Newman', 'gender': 2, 'depar...         Sam Mendes  
3  [{'name': 'Hans Zimmer', 'gender': 2, 'departm...  Christopher Nolan  
4  [{'name': 'Andrew Stanton', 'gender': 2, 'depa...     Andrew Stanton  

[5 rows x 24 columns]

In [4]:
# number of rows and columns in the data frame

movies_data.shape

(2089, 24)

In [5]:
# selecting the relevant features for recommendation

selected_features = ['genres','keywords','tagline','cast','director']
print(selected_features)

['genres', 'keywords', 'tagline', 'cast', 'director']


In [6]:
# replacing the null valuess with null string

for feature in selected_features:
  movies_data[feature] = movies_data[feature].fillna('')

In [7]:
# combining all the 5 selected features

combined_features = movies_data['genres']+' '+movies_data['keywords']+' '+movies_data['tagline']+' '+movies_data['cast']+' '+movies_data['director']

In [8]:
print(combined_features)

0       Action Adventure Fantasy Science Fiction cultu...
1       Adventure Fantasy Action ocean drug abuse exot...
2       Action Adventure Crime spy based on novel secr...
3       Action Crime Drama Thriller dc comics crime fi...
4       Action Adventure Science Fiction based on nove...
                              ...                        
2084    Action Thriller Science Fiction Horror video g...
2085    Adventure Action saving the world riddle nepal...
2086    Comedy Family Adventure Crime holiday new york...
2087    Science Fiction Drama indiana obsession extrat...
2088    Horror Thriller suicide hacker death of a frie...
Length: 2089, dtype: object


In [9]:
# converting the text data to feature vectors

vectorizer = TfidfVectorizer()

In [10]:
feature_vectors = vectorizer.fit_transform(combined_features)

In [11]:
print(feature_vectors)

  (0, 1301)	0.16876737376418685
  (0, 4275)	0.11680077942080784
  (0, 7161)	0.19237102342633866
  (0, 5581)	0.1604943595364643
  (0, 4793)	0.23336975078624914
  (0, 8027)	0.15792311079415675
  (0, 9152)	0.20976610112409733
  (0, 7703)	0.21597467308849047
  (0, 7318)	0.21272908808658564
  (0, 9520)	0.20704041734015702
  (0, 9370)	0.22357335105661574
  (0, 7336)	0.14736144586354316
  (0, 6285)	0.25697340044840095
  (0, 6107)	0.0925554685711143
  (0, 9366)	0.12198841805392979
  (0, 8387)	0.06908830353381445
  (0, 2703)	0.24717700071876755
  (0, 7829)	0.21272908808658564
  (0, 1726)	0.23957832275064228
  (0, 9098)	0.1251479022051235
  (0, 7889)	0.3209887190729286
  (0, 3222)	0.16400807874511147
  (0, 1646)	0.24717700071876755
  (0, 1985)	0.24717700071876755
  (0, 2974)	0.09753340234008673
  :	:
  (2088, 7862)	0.2746772642221126
  (2088, 7852)	0.2746772642221126
  (2088, 4136)	0.2746772642221126
  (2088, 9158)	0.2746772642221126
  (2088, 3458)	0.25073395104321083
  (2088, 5610)	0.2606713238

Cosine Similarity


In [12]:
# getting the similarity scores using cosine similarity

similarity = cosine_similarity(feature_vectors)

In [13]:
print(similarity)

[[1.         0.06444785 0.03430885 ... 0.00979879 0.01810682 0.00868979]
 [0.06444785 1.         0.02845527 ... 0.02122078 0.         0.01539724]
 [0.03430885 0.02845527 1.         ... 0.03988207 0.         0.        ]
 ...
 [0.00979879 0.02122078 0.03988207 ... 1.         0.         0.        ]
 [0.01810682 0.         0.         ... 0.         1.         0.02152174]
 [0.00868979 0.01539724 0.         ... 0.         0.02152174 1.        ]]


In [14]:
print(similarity.shape)

(2089, 2089)


Getting the movie name from the user

In [16]:
# getting the movie name from the user

movie_name = input(' Enter your favourite movie name : ')

 Enter your favourite movie name : iron man


In [18]:
# creating a list with all the movie names given in the dataset

list_of_all_titles = movies_data['title'].tolist()
print(list_of_all_titles)

['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre', 'The Dark Knight Rises', 'John Carter', 'Spider-Man 3', 'Tangled', 'Avengers: Age of Ultron', 'Harry Potter and the Half-Blood Prince', 'Batman v Superman: Dawn of Justice', 'Superman Returns', 'Quantum of Solace', "Pirates of the Caribbean: Dead Man's Chest", 'The Lone Ranger', 'Man of Steel', 'The Chronicles of Narnia: Prince Caspian', 'The Avengers', 'Pirates of the Caribbean: On Stranger Tides', 'Men in Black 3', 'The Hobbit: The Battle of the Five Armies', 'The Amazing Spider-Man', 'Robin Hood', 'The Hobbit: The Desolation of Smaug', 'The Golden Compass', 'King Kong', 'Titanic', 'Captain America: Civil War', 'Battleship', 'Jurassic World', 'Skyfall', 'Spider-Man 2', 'Iron Man 3', 'Alice in Wonderland', 'X-Men: The Last Stand', 'Monsters University', 'Transformers: Revenge of the Fallen', 'Transformers: Age of Extinction', 'Oz: The Great and Powerful', 'The Amazing Spider-Man 2', 'TRON: Legacy', 'Cars 2', 'Green Lant

In [19]:
# finding the close match for the movie name given by the user

find_close_match = difflib.get_close_matches(movie_name, list_of_all_titles)
print(find_close_match)

['Iron Man', 'Iron Man 3', 'Iron Man 2']


In [20]:
close_match = find_close_match[0]
print(close_match)

Iron Man


In [21]:
# finding the index of the movie with title

index_of_the_movie = movies_data[movies_data.title == close_match]['index'].values[0]
print(index_of_the_movie)

68


In [22]:
# getting a list of similar movies

similarity_score = list(enumerate(similarity[index_of_the_movie]))
print(similarity_score)

[(0, 0.028083927263748323), (1, 0.05088852429290338), (2, 0.010680531221142675), (3, 0.005018738220949115), (4, 0.026905538869299635), (5, 0.010490415668002927), (6, 0.08086137185048237), (7, 0.22129410720495182), (8, 0.0059309401848671225), (9, 0.06580064987629673), (10, 0.06607457866978897), (11, 0.008912303907761487), (12, 0.010496695441823543), (13, 0.009157156990512866), (14, 0.08476472871983082), (15, 0.005468555284454623), (16, 0.2124250864672975), (17, 0.00990551217026015), (18, 0.0388166666361485), (19, 0.0798296940059176), (20, 0.06681914028355694), (21, 0.008593537112203852), (22, 0.005267944937978601), (23, 0.004956071852402306), (24, 0.009053067741905684), (25, 0.0), (26, 0.20003794464922772), (27, 0.025923643303144454), (28, 0.05620635272989025), (29, 0.010557000915872817), (30, 0.06685849886788388), (31, 0.29758190265931844), (32, 0.03040396215488317), (33, 0.11404116020428036), (34, 0.0), (35, 0.03014890621347981), (36, 0.02743421238755173), (37, 0.005996204759672179), 

In [23]:
len(similarity_score)

2089

In [24]:
# sorting the movies based on their similarity score

sorted_similar_movies = sorted(similarity_score, key = lambda x:x[1], reverse = True)
print(sorted_similar_movies)

[(68, 1.0), (79, 0.3889042850565883), (31, 0.29758190265931844), (7, 0.22129410720495182), (16, 0.2124250864672975), (26, 0.20003794464922772), (85, 0.18758370811555494), (182, 0.17303940847499305), (511, 0.14896833152434866), (64, 0.13262188381528214), (203, 0.12962997621142125), (46, 0.12670168999602058), (174, 0.12630736817597718), (783, 0.12482495342000771), (101, 0.12451741468738077), (131, 0.1242058095665389), (1740, 0.12161867462604004), (138, 0.1215429049231857), (169, 0.12026318774392675), (94, 0.11955792407483229), (126, 0.116879863144568), (788, 0.11599717774566402), (33, 0.11404116020428036), (607, 0.11319234549708432), (1553, 0.11285523720554555), (353, 0.1124358687658105), (661, 0.11068978349663487), (1451, 0.11021824290525004), (720, 0.10276074058146226), (1210, 0.10219308920922245), (618, 0.10057999493940989), (1406, 0.09891010808137675), (954, 0.09785477245775806), (307, 0.09625905641451027), (800, 0.09539317688685003), (38, 0.09402629687846019), (122, 0.09228662822617

In [25]:
# print the name of similar movies based on the index

print('Movies suggested for you : \n')

i = 1

for movie in sorted_similar_movies:
  index = movie[0]
  title_from_index = movies_data[movies_data.index==index]['title'].values[0]
  if (i<30):
    print(i, '.',title_from_index)
    i+=1

Movies suggested for you : 

1 . Iron Man
2 . Iron Man 2
3 . Iron Man 3
4 . Avengers: Age of Ultron
5 . The Avengers
6 . Captain America: Civil War
7 . Captain America: The Winter Soldier
8 . Ant-Man
9 . X-Men
10 . X-Men: Apocalypse
11 . X2
12 . X-Men: Days of Future Past
13 . The Incredible Hulk
14 . Mortdecai
15 . X-Men: First Class
16 . G-Force
17 . Kick-Ass 2
18 . The Last Airbender
19 . Captain America: The First Avenger
20 . Guardians of the Galaxy
21 . Thor: The Dark World
22 . Deadpool
23 . X-Men: The Last Stand
24 . Sky Captain and the World of Tomorrow
25 . Se7en
26 . Tropic Thunder
27 . Zathura: A Space Adventure
28 . Zoom
29 . Contagion


Movie Recommendation Sytem

In [26]:
movie_name = input(' Enter your favourite movie name : ')

list_of_all_titles = movies_data['title'].tolist()

find_close_match = difflib.get_close_matches(movie_name, list_of_all_titles)

close_match = find_close_match[0]

index_of_the_movie = movies_data[movies_data.title == close_match]['index'].values[0]

similarity_score = list(enumerate(similarity[index_of_the_movie]))

sorted_similar_movies = sorted(similarity_score, key = lambda x:x[1], reverse = True)

print('Movies suggested for you : \n')

i = 1

for movie in sorted_similar_movies:
  index = movie[0]
  title_from_index = movies_data[movies_data.index==index]['title'].values[0]
  if (i<30):
    print(i, '.',title_from_index)
    i+=1

 Enter your favourite movie name : bat man
Movies suggested for you : 

1 . Batman
2 . Batman Returns
3 . Batman & Robin
4 . The Dark Knight Rises
5 . Batman Begins
6 . The Dark Knight
7 . Bedazzled
8 . A History of Violence
9 . The Sentinel
10 . Planet of the Apes
11 . Superman
12 . Mars Attacks!
13 . Man of Steel
14 . Suicide Squad
15 . Spider-Man 3
16 . Spider-Man 2
17 . Jonah Hex
18 . Reds
19 . I Dreamed of Africa
20 . Multiplicity
21 . Superman Returns
22 . Something's Gotta Give
23 . Green Lantern
24 . Sweet November
25 . The One
26 . Superman II
27 . Superman III
28 . Cellular
29 . Blood and Wine
